AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

  